//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Role.cpp
//  @ Date : 29-03-2021
//  @ Author : 
//
//


#include "Role.h"

void Role::addRole() {

}

void Role::editRole() {

}

void Role::deleteRole() {

}

